/* Generated By:JavaCC: Do not edit this line. RegexConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RegexConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXPR1 = 4;
  /** RegularExpression Id. */
  int EXPR2 = 5;
  /** RegularExpression Id. */
  int EXPR3 = 6;
  /** RegularExpression Id. */
  int LF = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<EXPR1>",
    "<EXPR2>",
    "<EXPR3>",
    "\"\\n\"",
  };

}
